### ISSUE TITLE
canonicalize() does not always place sequant::NormalOperators to the right of sequant::Tensors

### ISSUE THREAD

**Issue by cmasteran1** [ValeevGroup/SeQuant2#61]
While working with Tensors with labels outside the cardinal_tensor_labels list, Canonicalize does not know to put operators after tensors.  After some investigation, it seems that TensorNetwork.canonicalize() is never thrown even when it should be (Products that contain anything besides sequant::Tensor). The easy current workaround is to simply add the tensor label to the list. However, it would make sense that sequant::NormalOperators should always be placed to the right of sequant::Tensors since the wick engine requires  sequant::NormalOperators to be on the right end of a product.

**Comment by evaleev** [comment]
@cmasteran1 if using custom tensor label for operators should add them to the end of `sequant::mbpt::cardinal_tensor_labels` ... + add check in the wick engine to ensure that ops are at the end.
